/**
 * This js file is used to convert `./reports/registries.json` generated by data generator to `shared` files.
 * Put the `registries.json` file in the same directory as the js file.
 * Use `node ./get.js` to execute.
 * 
 * @author SPGoding
 */

const fs = require('fs')

const registriesJson = JSON.parse(fs.readFileSync('./registries.json', { encoding: 'utf8' }))

function convert(keyName, fileName) {
    const arr = []
    let ans = `{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/Levertion/minecraft-json-schema/master/java/shared/${fileName}.json",
    "type": "string",
    "enum": [
`
    for (const id in registriesJson[keyName].entries) {
        arr.push(`        "${id}",`)
    }
    ans += arr.join('\n').slice(0, -1)
    ans += `
    ]
}`
    fs.writeFileSync(`../java/shared/${fileName}.json`, ans)
}

convert('minecraft:sound_event', 'sound_event')
convert('minecraft:fluid', 'fluid_name')
convert('minecraft:mob_effect', 'effect_name')
convert('minecraft:block', 'block_name')
convert('minecraft:enchantment', 'enchantment_name')
convert('minecraft:entity_type', 'entity_name')
convert('minecraft:potion', 'potion_name')
convert('minecraft:biome', 'biome_name')
convert('minecraft:particle_type', 'particle_name')
convert('minecraft:block_entity_type', 'block_entity_name')
convert('minecraft:dimension_type', 'dimension_name')
convert('minecraft:villager_type', 'villager_type')
convert('minecraft:villager_profession', 'villager_profession')